spring:
  application:
    name: MuscleShop1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/musclesh_dev_web
    username: root
    password: 123456789
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
