spring:
  application:
    name: MuscleShop1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/musclesh_aclopation
    username: root
    password: 123456789
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
